server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/regist
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: mcc76.mii@gmail.com
    password: jlgisnqedtojizii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql:
    show-sql: true